blueprint:
  name: Heating Control
  description: Control your heating with options for person home, if temp is below a specific value, set temp, and heating between specific times.
  domain: automation
  input:
    heating:
      name: Climate Device
      description: The climate device to use.
      selector:
        entity:
          domain: climate
    temp_sensor:
      name: Temperature Sensor
      description: Temperature Sensor to check.
      selector:
        entity:
          domain: sensor
          device_class: temperature
    person1:
      name: Person 1
      description: The first person that has to be home.
      default: []
      selector:
        entity:
